theme: jekyll-theme-cayman
title: El juego del HeRrero
author: Gabriel González Medina
navbar-links:
  About Me: "Psicólogo, Magister en Epidemiología. Mail de contacto :  gagonzalez1@uc.cl"
markdown: kramdown
# Reading Files
include: index.html
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
