theme: jekyll-theme-cayman
title: El juego del HeRrero
author: Gabriel González Medina
navbar-links:
  About Me: "Psicólogo U de Chile, Magister en Epidemiología y estudiante de Doctorado en Epidemiología (P. Universidad Católica de Chile) Mail de contacto :  gagonzalez1@uc.cl"


base_url: El-juego-del-heRrero/docs
url: https://gagonzalezm.github.io/El-juego-del-heRrero/


markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
